[package]
name = "blackhosts"
version = "1.0.109134"
authors = ["flux"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# easy = "0.1.1
curl = "0.4.34"
recolored = "1.9.3"
regex = "1.4.2"
md5 = "0.7.0"