name: Debian Build

on:
  push:
    branches:
      - debian
jobs:
  build_and_test_debian:
    name: Rust Debian Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Remove Redundant
        run: |
          rm -rf target/release/.fingerprint
          rm -rf target/release/build
          rm -rf target/release/deps
          rm -f target/release/.cargo-lock
          rm -f target/.rustc_info.json
          rm -f target/release/blackhosts.d
          rm -rf /target/release/blackhosts.deb
      - name: Check for project files
        run: |
          [[ -f "./target/release/blackhosts" ]] || exit 1
          [[ -d "./debian/usr/bin" ]] || exit 2
      - name: Setup Deb Package Build
        run: |
          cp "./target/release/blackhosts" "./debian/usr/bin/blackhosts" || exit 1
      - name: Build Deb Package
        run: |
          dpkg-deb --build "./debian" "./target/release/blackhosts.deb" || exit 1
      - name: Push Changes
        run: |
          git pull origin debian
          git config --global user.name "Lateralus138"
          git config --global user.email "faithnomoread@yahoo.com"
          git add target/release/blackhosts.deb
          git commit --allow-empty -m "Debian Build Compile & Test"
          git push -u origin debian --force
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: 1.0.0.0
          name: Stable Release
          prerelease: False
          artifacts: "target/release/blackhosts.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
