name: Windows Build

on:
  push:
    branches:
      - windows

jobs:
  build_and_test_windows:
    name: Rust Windows Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Remove Redundant
        run: |
          Remove-Item -Recurse -Path '.\target\release\.fingerprint' -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Path '.\target\release\build' -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Path '.\target\release\deps' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\target\release\.cargo-lock' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\target\release\blackhosts.d' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\target\release\blackhosts.pdb' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\target\.rustc_info.json' -ErrorAction SilentlyContinue
          Remove-Item -Path '.\target\release\blackhosts_windows.exe' -ErrorAction SilentlyContinue
      - name: Rename Bin
        run: |
          Rename-Item -Path '.\target\release\blackhosts.exe' -NewName 'blackhosts_windows.exe'
      - name: Push Changes
        run: |
          git pull origin windows
          git config --global user.name "Lateralus138"
          git config --global user.email "faithnomoread@yahoo.com"
          git add .
          git commit --allow-empty -m "Windows Build Compile & Test"
          git push -u origin windows --force
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          tag: 1.0.0.0
          name: Stable Release
          prerelease: False
          artifacts: "target/release/blackhosts_windows.exe"
          token: ${{ secrets.GITHUB_TOKEN }}